Add friends likes
Val2003/java-filmorate pull request #22
Opened 2023-05-16 05:24 UTC by Val2003

2023-05-16 15:57 UTC, andrew-larkin requested changes
Привет! Очень хорошо, код чистый, структура приложения и новый функционал реализованы качественно. У меня всего 2 предложения по улучшению, но на твое усмотрение.

2023-05-16 15:57 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    public FilmController(FilmService filmService) {
чтобы в контроллерах не создавать конструкторы, мы можем поставить над классом @RequiredArgsConstructor и тогда все переменные, помеченные как final, будут автоматом добавляться в неявный конструктор - таким образом будет обеспечено внедрение зависимости

2023-05-16 15:57 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/FilmControllerTest.java
> +    @Test
тесты хорошие. если будет время и желание, предлагаю вместо httpClient использовать MockMvc - он выполняет все то же самое, но мы можем делать assert'ы сразу при получении ответа, удобно

2023-05-18 18:28 UTC, Val2003 commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    public FilmController(FilmService filmService) {
Поправил

2023-05-28 19:51 UTC, merged